'use client'
import Head from 'next/head';
import gsap from 'gsap';
import { useLayoutEffect, useRef } from "react";
import Background from './components/Background/Background';
import Thumbnail from './components/Thumbnail/Thumbnail';

export default function Page() {

  return (
    <>
      <Head>
        <title>Diego Caviedes Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex min-h-screen max-h-screen items-center justify-center">
        <section>
          <Background></Background>
          <Thumbnail></Thumbnail>
        </section>
      </main>
    </>
  );
}
