
import Head from 'next/head';
import Background from './components/Background/Background';

export default function Home() {
  return (
    <>
      <Head>
        <title>Diego Caviedes Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex min-h-screen items-center justify-center bg-[--color-background]]">
        <section>
          <Background></Background>
          <div className="text-center">
            <h1 className="text-white text-4xl">Diego</h1>
            <h1 className='text-white text-4xl'>Caviedes Aguirre</h1>
          </div>
        </section>
      </main>
    </>
  );
}
