import Background from "@/components/Background/Background";
import Thumbnail from "@/components/Thumbnail/Thumbnail";
import Link from "next/link";
import Head from 'next/head';

export default function About() {
    return (
        <>
            <Head>
            <title>Diego Caviedes Website</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className="flex flex-col min-h-screen z-10">
                <Background></Background>
                <section id='Thumbnail' className='flex min-h-screen max-h-screen min-w-full items-center justify-center relative'>
                    
                </section>
            </main>
        </>
    )
}