import Link from "next/link";
import Head from 'next/head';

import Background from "@/components/Background/Background";
import ThumbnailAbout from "@/components/ThumbnailAbout/ThumbnailAbout";
import ScrollLine from "@/components/ScrollLine/ScrollLine";
import ContactCarousel from "@/components/ContactCarousel/ContactCarousel";
import TechnologiesSection from "@/components/TechnologiesSection/TechnologiesSection";
import AboutDraggable from "@/components/AboutDraggable/AboutDraggable";

export default function About() {
    return (
        <>
            <Head>
            <title>Diego Caviedes Website</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            </Head>
            <main className="flex flex-col min-h-screen z-10">
                <Background></Background>
                <section id='ThumbnailAbout' className='flex min-h-screen max-h-screen min-w-full items-center justify-center relative p-0'>
                    <ThumbnailAbout></ThumbnailAbout>
                    <ScrollLine height={7}></ScrollLine>
                </section>
                <section id='AboutMe' className='min-w-full px-0 py-16 relative'>
                    <AboutDraggable></AboutDraggable>
                </section>
                <section id='Technologies' className='flex min-h-screen max-h-screen min-w-full items-center relative p-0'>
                    <TechnologiesSection></TechnologiesSection>
                </section>
                <section id='ContactMe' className='p-0'>
                    <ContactCarousel></ContactCarousel>
                </section>
            </main>
        </>
    )
}