import Background from "@/components/Background/Background";
import KCLPThumbnail from "@/components/KCLPThumbnail/KCLPThumbnail";
import Head from "next/head";

export default function KCLPARTPage() {
  return (
    <>
      <Head>
        <title>Diego Caviedes Website</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="flex flex-col min-h-screen z-10">
        <Background></Background>
        <section
          id="Thumbnail"
          className="flex min-h-screen w-full px-0 pb-0 pt-10 inset-0 relative"
        >
          <KCLPThumbnail></KCLPThumbnail>
        </section>
      </main>
    </>
  );
}
